export const REQUEST_TYPE = {
  COMMUNICATION_REQUEST: 'COMMUNICATION_REQUEST',
  COMMUNICATION_RESPONSE: 'COMMUNICATION_RESPONSE',
  DELETE_PIECE_REQUEST: 'DELETE_PIECE_REQUEST',
  DISCOVERY_REQUEST: 'DISCOVERY_REQUEST',
  LIST_GAMES_REQUEST: 'LIST_GAMES_REQUEST',
  MOVE_REQUEST: 'MOVE_REQUEST',
  PICK_UP_PIECE_REQUEST: 'PICK_UP_PIECE_REQUEST',
  PLACE_DOWN_PIECE_REQUEST: 'PLACE_DOWN_PIECE_REQUEST',
  REFRESH_STATE_REQUEST: 'REFRESH_STATE_REQUEST',
  REGISTER_GAME_REQUEST: 'REGISTER_GAME_REQUEST',
  TEST_PIECE_REQUEST: 'TEST_PIECE_REQUEST',
  UNREGISTER_GAME_REQUEST: 'UNREGISTER_GAME_REQUEST'
};
